services:
  postgres:
    image: postgres:17
    container_name: go-notes-postgres-compose
    restart: unless-stopped
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notessecret
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notesuser -d notesdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: go-notes-api-compose
    restart: unless-stopped
    environment:
      APP_PORT: "8080"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASSWORD: notessecret
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:1.27
    container_name: go-notes-nginx-compose
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  reporter:
    build:
      context: .
      dockerfile: Dockerfile.reporter
    container_name: go-notes-reporter-compose
    restart: unless-stopped
    environment:
      TARGET_URL: http://nginx/healthz
      CHECK_INTERVAL_SECONDS: "10"
      REPORT_EVERY_N_CHECKS: "3"
      RUN_MODE: loop
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASSWORD: notessecret
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
      nginx:
        condition: service_started
    volumes:
      - ./reporter/reports:/app/reports

volumes:
  postgres_data:
