FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY reporter/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY reporter/reporter.py .
RUN mkdir -p /app/reports

CMD ["python", "reporter.py"]
